use std::collections::{BTreeMap, HashSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use mavlink_bindgen::parser::{extra_crc, parse_profile, MavEnum, MavField, MavProfile, MavType};

/// Top-level dialect parsed for descriptors; its includes pull in `common.xml` etc. This matches
/// the `dialect-ardupilotmega` feature the `mavlink` baseline is compiled with. Every message in
/// the resolved profile gets a descriptor; correctness is enforced by the whole-dialect property
/// test against the `rust-mavlink` + `serde_json` baseline.
const DIALECT: &str = "ardupilotmega.xml";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    compile_c_reference_shim();

    if std::env::var_os("CARGO_FEATURE_JSON").is_some() {
        generate_descriptors();
    }
}

fn generate_descriptors() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let defs_dir = manifest_dir.join("third_party/mavlink_message_definitions/v1.0");
    println!("cargo:rerun-if-changed={}", defs_dir.display());

    let mut parsed_files: HashSet<PathBuf> = HashSet::new();
    let profile = parse_profile(&defs_dir, Path::new(DIALECT), &mut parsed_files)
        .unwrap_or_else(|e| panic!("failed to parse {DIALECT}: {e:?}"));

    let code = emit_module(&profile);

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("mavlink_json_generated.rs");
    std::fs::write(&out, code).expect("failed to write generated descriptors");
}

fn emit_module(profile: &MavProfile) -> String {
    let mut enum_tables: BTreeMap<String, String> = BTreeMap::new();
    let mut fields_code = String::new();
    let mut msgs_code = String::new();
    let mut dispatch = String::new();
    let mut dispatch_by_name = String::new();

    for msg in profile.messages.values() {
        let name = &msg.name;

        let mut offset: usize = 0;
        let mut base_len: usize = 0;
        let mut fields = String::new();
        for field in &msg.fields {
            let kind = field_kind(profile, field, &mut enum_tables);
            let _ = writeln!(
                fields,
                "    FieldDesc {{ name: {:?}, offset: {}, kind: {} }},",
                field.name, offset, kind
            );
            offset += mav_len(&field.mavtype);
            // Base (non-extension) fields are contiguous at the front; MAVLink v1 frames carry
            // exactly these and never the extension fields.
            if !field.is_extension {
                base_len += mav_len(&field.mavtype);
            }
        }

        let fields_ident = format!("FIELDS_{name}");
        let msg_ident = format!("MSG_{name}");
        let _ = writeln!(
            fields_code,
            "static {fields_ident}: &[FieldDesc] = &[\n{fields}];"
        );
        let _ = writeln!(
            msgs_code,
            "static {msg_ident}: MsgDesc = MsgDesc {{ id: {}, name: {:?}, payload_len: {}, base_len: {}, crc_extra: {}, fields: {fields_ident} }};",
            msg.id, msg.name, offset, base_len, extra_crc(msg)
        );
        let _ = writeln!(dispatch, "        {} => Some(&{msg_ident}),", msg.id);
        let _ = writeln!(
            dispatch_by_name,
            "        b{:?} => Some(&{msg_ident}),",
            msg.name
        );
    }

    let mut code = String::new();
    code.push_str("// @generated by build.rs from vendored MAVLink XML. Do not edit.\n");
    code.push_str("use crate::mavlink_json::rt::{FieldDesc, FieldKind, MsgDesc, ScalarKind};\n\n");
    for table in enum_tables.values() {
        code.push_str(table);
    }
    code.push('\n');
    code.push_str(&fields_code);
    code.push('\n');
    code.push_str(&msgs_code);
    code.push_str(
        "\n/// Returns the descriptor for a MAVLink message id, if it is generated.\n\
         pub fn descriptor(id: u32) -> Option<&'static MsgDesc> {\n    match id {\n",
    );
    code.push_str(&dispatch);
    code.push_str("        _ => None,\n    }\n}\n");
    code.push_str(
        "\n/// Returns the descriptor for a MAVLink message name (the serde `\"type\"` tag).\n\
         pub fn descriptor_by_name(name: &[u8]) -> Option<&'static MsgDesc> {\n    match name {\n",
    );
    code.push_str(&dispatch_by_name);
    code.push_str("        _ => None,\n    }\n}\n");
    code
}

/// Renders the `FieldKind` constructor for a field, registering any enum/bitmask name table it
/// needs into `enum_tables` (keyed by the generated static ident, so each is emitted once).
///
/// Aggregate types are matched first: rust-mavlink's `emit_type` renders any array with the
/// primitive element type (the `enum=` attribute is ignored for arrays), so an enum/bitmask array
/// serializes as a plain numeric array and is treated as one here.
fn field_kind(
    profile: &MavProfile,
    field: &MavField,
    enum_tables: &mut BTreeMap<String, String>,
) -> String {
    match &field.mavtype {
        MavType::CharArray(len) => format!("FieldKind::CharArray({len})"),
        MavType::Array(inner, len) => format!("FieldKind::Array({}, {len})", scalar_kind(inner)),
        scalar => {
            if let Some(enum_name) = &field.enumtype {
                let table_ident = enum_table_ident(enum_name);
                enum_tables
                    .entry(table_ident.clone())
                    .or_insert_with(|| emit_enum_table(profile, enum_name, &table_ident));
                let sk = scalar_kind(scalar);
                if field.display.as_deref() == Some("bitmask") {
                    format!("FieldKind::Bitmask({table_ident}, {sk})")
                } else {
                    format!("FieldKind::Enum({table_ident}, {sk})")
                }
            } else {
                format!("FieldKind::Scalar({})", scalar_kind(scalar))
            }
        }
    }
}

fn emit_enum_table(profile: &MavProfile, enum_name: &str, table_ident: &str) -> String {
    let en: &MavEnum = profile
        .enums
        .get(enum_name)
        .unwrap_or_else(|| panic!("enum {enum_name} not found"));
    let mut body = String::new();
    for entry in &en.entries {
        // Skip synthetic/valueless entries (e.g. `_ENUM_END`); serde never emits them.
        if let Some(value) = entry.value {
            let _ = writeln!(body, "    ({value}, {:?}),", entry.name);
        }
    }
    format!("static {table_ident}: &[(u64, &str)] = &[\n{body}];\n")
}

fn enum_table_ident(pascal_name: &str) -> String {
    format!("ENUM_{}", pascal_to_screaming(pascal_name))
}

fn pascal_to_screaming(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i != 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_uppercase());
    }
    out
}

/// Maps a MAVLink primitive (or array element) to a `rt::ScalarKind` path.
fn scalar_kind(t: &MavType) -> &'static str {
    match t {
        MavType::UInt8MavlinkVersion | MavType::UInt8 | MavType::Char => "ScalarKind::U8",
        MavType::UInt16 => "ScalarKind::U16",
        MavType::UInt32 => "ScalarKind::U32",
        MavType::UInt64 => "ScalarKind::U64",
        MavType::Int8 => "ScalarKind::I8",
        MavType::Int16 => "ScalarKind::I16",
        MavType::Int32 => "ScalarKind::I32",
        MavType::Int64 => "ScalarKind::I64",
        MavType::Float => "ScalarKind::F32",
        MavType::Double => "ScalarKind::F64",
        MavType::CharArray(_) | MavType::Array(_, _) => {
            panic!("scalar_kind called on aggregate type")
        }
    }
}

/// Wire byte length of a field type (element size times count for arrays).
fn mav_len(t: &MavType) -> usize {
    match t {
        MavType::UInt8MavlinkVersion | MavType::UInt8 | MavType::Int8 | MavType::Char => 1,
        MavType::UInt16 | MavType::Int16 => 2,
        MavType::UInt32 | MavType::Int32 | MavType::Float => 4,
        MavType::UInt64 | MavType::Int64 | MavType::Double => 8,
        MavType::CharArray(len) => *len,
        MavType::Array(inner, len) => mav_len(inner) * len,
    }
}

fn compile_c_reference_shim() {
    // The C reference shim is only compiled for the opt-in benchmark arm so that normal
    // builds need neither a C compiler nor the c_library_v2 submodule.
    if std::env::var_os("CARGO_FEATURE_BENCH_C_REFERENCE").is_none() {
        return;
    }

    let lib_root = std::path::Path::new("third_party/c_library_v2");
    assert!(
        lib_root.join("ardupilotmega/mavlink.h").exists(),
        "the `bench-c-reference` feature requires the c_library_v2 submodule; run \
         `git submodule update --init third_party/c_library_v2`"
    );

    println!("cargo:rerun-if-changed=benches/c_shim/shim.c");

    cc::Build::new()
        .file("benches/c_shim/shim.c")
        .include(lib_root)
        .warnings(false)
        .flag_if_supported("-Wno-address-of-packed-member")
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-unused-function")
        .compile("mavlink_c_shim");
}
