//! Descriptor tables generated by `build.rs` from the vendored MAVLink XML definitions.
//!
//! The generated code is pure data ([`crate::mavlink_json::rt::MsgDesc`] tables); all transcoding
//! logic lives in [`crate::mavlink_json::rt`]. See `build.rs` for the generator.
#![allow(non_upper_case_globals)]

include!(concat!(env!("OUT_DIR"), "/mavlink_json_generated.rs"));
