name: Test and Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            TARGET: x86_64-unknown-linux-musl

          - os: macos-latest
            TARGET: x86_64-apple-darwin

          - os: windows-latest
            TARGET: x86_64-pc-windows-msvc

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use cached dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: "${{ matrix.os }}-${{ matrix.TARGET }}-${{ hashFiles('**/Cargo.lock') }}"
          shared-key: "shared"

      - name: Install build dependencies - Rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable --profile minimal --target ${{ matrix.TARGET }} -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install build dependencies - musl
        if: matrix.TARGET == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Building lib for ${{ matrix.os }} ${{ matrix.target }}
        run: cargo build --release --locked --target ${{matrix.target}} --verbose

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Compile all targets for ${{ matrix.os }} ${{ matrix.target }}
        run: cargo test --all-targets --no-run --locked --target ${{matrix.target}} --verbose

      - name: Running tests for ${{ matrix.os }} ${{ matrix.target }}
        run: cargo xtask test -- --target ${{matrix.target}} --verbose

  miri:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use cached dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: "miri-${{ hashFiles('**/Cargo.lock') }}"
          shared-key: "shared"

      - name: Install Miri
        run: |
          rustup toolchain install nightly --profile minimal
          rustup component add miri --toolchain nightly
          cargo +nightly miri setup

      - name: Miri
        run: cargo xtask miri
